import React from "react";
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Providers from "@/app/providers";
import { Layout } from "antd";
import { Footer, Header } from "antd/es/layout/layout";
import "@styles/global.css"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
    </head>
    <body
      className={"m-0"}
    >
    <Providers>
      <Layout>
        {children}
      </Layout>
    </Providers>
    </body>
    </html>

  )
}
