import React from "react";
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Providers from "@/app/providers";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
    </head>
    <body
      className={"m-0"}
    >
    <Providers>
      {children}
    </Providers>
    </body>
    </html>

  )
}
