# Generated by Django 4.2.8 on 2023-12-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=1024)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospedes', models.IntegerField()),
                ('beneficios', models.ManyToManyField(to='hoteis.beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=1024)),
                ('endereco', models.CharField(max_length=1024)),
                ('avaliacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hoteis.categoriaquarto')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteis.hotel')),
            ],
        ),
    ]
