# Generated by Django 4.2.8 on 2024-01-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('autorizacao', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteis.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='EspacoHotelReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicial', models.DateTimeField()),
                ('duracao', models.DurationField()),
                ('idEspaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteis.espacohotel')),
            ],
        ),
    ]
