# Generated by Django 4.2.8 on 2024-01-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0003_alter_reserva_options_reserva_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
    ]
