# Generated by Django 4.2.8 on 2024-02-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0002_espacohotel_espacohotelreserva'),
        ('hoteis', '0004_alter_reserva_options'),
    ]

    operations = [
    ]
