# Generated by Django 4.2.8 on 2024-02-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0004_alter_reserva_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='categoriaquarto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='categorias'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='estado',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagem',
            field=models.ImageField(null=True, upload_to='hoteis'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rua',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
