# Generated by Django 4.2.8 on 2024-02-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0005_rename_endereco_hotel_cidade_categoriaquarto_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hospedes',
        ),
    ]
