# Generated by Django 4.2.8 on 2024-02-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteis', '0005_merge_20240203_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacohotel',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
